### ISSUE TITLE
Publish the crate with 0.4.0 chrono because it is impossible to compile!

### ISSUE THREAD

**Issue by iddm** [azyobuzin/tweetust#6]
Hey! Nobody is able to use your crate anymore - you have merged #5 which changes the version of `chrono` to 0.4 but did not publish the crate, so everyone sees your old crate which uses yanked version of chrono!

https://github.com/dmizuk/twitter-stream-rs/issues/14

**Comment by azyobuzin** [comment]
I've released v0.8.0!

**Comment by iddm** [comment]
Thanks!
